// ============================================================
// KABUTT ONLINE — Mock Data v4
// Imágenes locales — 5 fotos de zapatos generadas y guardadas en /images/
// Sin dependencia de CDN externo
// ============================================================

const SHOE_FALLBACK_SVG = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600" viewBox="0 0 600 600"><rect width="600" height="600" fill="#F0F0F0"/><text x="300" y="320" text-anchor="middle" font-size="16" font-family="Arial,sans-serif" fill="#aaa" letter-spacing="4">KABUTT</text></svg>`)}`;

// ═══ POOL DE 5 IMÁGENES LOCALES DE ZAPATOS ════════════════════
// Oxford / Derby cuero hombre — marrón elegante
const I_CUERO_H = 'images/oxford.jpg';
// Mocasín cuero — loafer camel
const I_MOCASIN = 'images/loafer.jpg';
// Botín / Chelsea boot — cuero negro
const I_BOTIN   = 'images/chelsea.jpg';
// Zapatilla casual cuero — blanco/gris
const I_CASUAL  = 'images/sneaker.jpg';
// Zapato/sandalia mujer — nude/beige
const I_MUJER   = 'images/sandal.jpg';

// Aliases por tipo de producto
const I_OXFORD_BLK  = I_CUERO_H;
const I_OXFORD_BLK2 = I_BOTIN;    // hover: chelsea (distinto)
const I_DERBY_BRN   = I_CUERO_H;
const I_DERBY_BRN2  = I_MOCASIN;  // hover: loafer (distinto)
const I_LOAFER      = I_MOCASIN;
const I_LOAFER2     = I_CUERO_H;  // hover: oxford (distinto)
const I_CHELSEA_H   = I_BOTIN;
const I_CHELSEA_H2  = I_CUERO_H;  // hover: oxford (distinto)
const I_BOTIN_W     = I_MUJER;
const I_BOTIN_W2    = I_CASUAL;   // hover: sneaker (distinto)
const I_SANDAL_W    = I_MUJER;
const I_SANDAL_W2   = I_MOCASIN;  // hover: loafer (distinto)
const I_CASUAL_W    = I_CASUAL;
const I_CASUAL_B    = I_MOCASIN;  // hover: loafer (distinto)
const I_PUMP_W      = I_MUJER;
const I_FLAT_W      = I_BOTIN;    // hover: chelsea (distinto)

// Hero y editorial usan campaña y oxford respectivamente
const HERO_IMAGE      = 'images/campaign.jpg';
const EDITORIAL_IMAGE = I_CUERO_H;

// Función IMG ahora es solo un pass-through (ya no usamos Unsplash)
const IMG = (id) => id;





const mockShoes = [
  {
    id: 1,
    name: 'Oxford de Cuero Negro Clásico',
    brand: 'KABUTT',
    category: 'vestir',
    gender: 'hombre',
    price: 239.90,
    oldPrice: 319.90,
    discount: 25,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    availableSizes: [39, 40, 41, 42, 43],
    color: 'Negro',
    colorHex: '#1a1a1a',
    material: 'Cuero genuino',
    sole: 'Suela de cuero',
    insole: 'Plantilla de espuma de memoria',
    lastType: 'Horma clásica',
    stock: 12,
    image: I_OXFORD_BLK,
    images: [I_OXFORD_BLK, I_OXFORD_BLK2, I_CHELSEA_H],
    description: 'Oxford de cuero genuino con diseño clásico. Ideal para entornos formales, ejecutivos y reuniones de negocios. Costura blake de alta resistencia. Horma anatómica para uso prolongado.',
    sku: 'KB-VES-001-NEG',
    isNew: false,
    isFeatured: true,
    isOffer: true,
  },
  {
    id: 2,
    name: 'Derby Cuero Marrón Ejecutivo',
    brand: 'KABUTT',
    category: 'vestir',
    gender: 'hombre',
    price: 259.90,
    oldPrice: 339.90,
    discount: 24,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    availableSizes: [39, 40, 41, 42, 43],
    color: 'Marrón',
    colorHex: '#7A4A2B',
    material: 'Cuero vacuno pulido',
    sole: 'Suela de cuero con patín de goma',
    insole: 'Plantilla anatómica de cuero',
    lastType: 'Horma clásica italiana',
    stock: 8,
    image: I_DERBY_BRN,
    images: [I_DERBY_BRN, I_DERBY_BRN2],
    description: 'Derby de cuero vacuno en tono marrón. Corte limpio con terminaciones cosidas a mano. Forro interior de cuero natural transpirable. El zapato indispensable del ejecutivo moderno.',
    sku: 'KB-VES-002-MAR',
    isNew: false,
    isFeatured: true,
    isOffer: true,
  },
  {
    id: 3,
    name: 'Botín Cuero Mujer Nude',
    brand: 'KABUTT',
    category: 'botin',
    gender: 'mujer',
    price: 279.90,
    oldPrice: null,
    discount: 0,
    sizes: [35, 36, 37, 38, 39, 40],
    availableSizes: [35, 36, 37, 38, 39],
    color: 'Nude',
    colorHex: '#C4A882',
    material: 'Cuero nappa',
    sole: 'Suela sintética de alta resistencia',
    insole: 'Plantilla de cuero natural',
    lastType: 'Horma puntera redonda',
    stock: 5,
    image: I_BOTIN_W,
    images: [I_BOTIN_W, I_BOTIN_W2],
    description: 'Botín de cuero nappa en tono nude, con tacón bloque de 5 cm. Cierre lateral con cremallera metálica. Diseño femenino y elegante para el día a día.',
    sku: 'KB-BOT-003-NUD',
    isNew: true,
    isFeatured: true,
    isOffer: false,
  },
  {
    id: 4,
    name: 'Mocasín Cuero Camel Casual',
    brand: 'KABUTT',
    category: 'mocasin',
    gender: 'hombre',
    price: 199.90,
    oldPrice: 249.90,
    discount: 20,
    sizes: [38, 39, 40, 41, 42, 43],
    availableSizes: [39, 40, 41, 42],
    color: 'Camel',
    colorHex: '#C19A6B',
    material: 'Cuero vacuno liso',
    sole: 'Suela de goma antideslizante',
    insole: 'Plantilla anatómica acolchada',
    lastType: 'Horma semiplana',
    stock: 14,
    image: I_LOAFER,
    images: [I_LOAFER, I_LOAFER2],
    description: 'Mocasín de cuero vacuno con acabado liso. Diseño casual-elegante perfecto para el día a día. Suela de goma para mayor adherencia y comodidad en todo terreno.',
    sku: 'KB-MOC-004-CAM',
    isNew: false,
    isFeatured: true,
    isOffer: true,
  },
  {
    id: 5,
    name: 'Chelsea Boot Cuero Negro',
    brand: 'KABUTT',
    category: 'botin',
    gender: 'hombre',
    price: 319.90,
    oldPrice: null,
    discount: 0,
    sizes: [39, 40, 41, 42, 43, 44],
    availableSizes: [39, 40, 41, 42, 43],
    color: 'Negro',
    colorHex: '#1a1a1a',
    material: 'Cuero genuino curtido al vegetal',
    sole: 'Suela de goma de alta resistencia',
    insole: 'Plantilla ortopédica ergonómica',
    lastType: 'Horma cuadrada moderna',
    stock: 9,
    image: I_CHELSEA_H,
    images: [I_CHELSEA_H, I_CHELSEA_H2],
    description: 'Chelsea boot de cuero negro curtido al vegetal. Elásticos laterales de alta resistencia. Suela de goma gruesa antideslizante. Estilo urbano-elegante para hombre moderno.',
    sku: 'KB-BOT-005-NEG',
    isNew: true,
    isFeatured: true,
    isOffer: false,
  },
  {
    id: 6,
    name: 'Sandalia Cuero Mujer Camel',
    brand: 'KABUTT',
    category: 'sandalia',
    gender: 'mujer',
    price: 119.90,
    oldPrice: 159.90,
    discount: 25,
    sizes: [35, 36, 37, 38, 39, 40],
    availableSizes: [35, 36, 37, 38, 39, 40],
    color: 'Camel',
    colorHex: '#C19A6B',
    material: 'Cuero genuino',
    sole: 'Suela de EVA ultraliviana',
    insole: 'Plantilla de cuero con acolchado',
    lastType: 'Horma plana',
    stock: 20,
    image: I_SANDAL_W,
    images: [I_SANDAL_W, I_SANDAL_W2],
    description: 'Sandalia plana de cuero genuino con tiras ajustables. Cómoda y resistente. Diseño urban-chic para el clima peruano. Plantilla ergonómica de cuero.',
    sku: 'KB-SAN-006-CAM',
    isNew: false,
    isFeatured: true,
    isOffer: true,
  },
  {
    id: 7,
    name: 'Mocasín Cuero Oscuro Premium',
    brand: 'KABUTT',
    category: 'mocasin',
    gender: 'hombre',
    price: 229.90,
    oldPrice: 279.90,
    discount: 18,
    sizes: [39, 40, 41, 42, 43, 44],
    availableSizes: [39, 40, 41, 42, 43],
    color: 'Marrón oscuro',
    colorHex: '#5C3317',
    material: 'Cuero vacuno premium',
    sole: 'Suela de cuero reforzado',
    insole: 'Plantilla de espuma de alta densidad',
    lastType: 'Horma italiana slim',
    stock: 11,
    image: I_LOAFER2,
    images: [I_LOAFER2, I_LOAFER],
    description: 'Mocasín de cuero vacuno en tono oscuro con forro interior de tela y suela de cuero reforzado. Elegancia italiana en cada paso.',
    sku: 'KB-MOC-007-OSC',
    isNew: false,
    isFeatured: false,
    isOffer: true,
  },
  {
    id: 8,
    name: 'Stiletto Cuero Nude Elegante',
    brand: 'KABUTT',
    category: 'vestir',
    gender: 'mujer',
    price: 289.90,
    oldPrice: 359.90,
    discount: 19,
    sizes: [35, 36, 37, 38, 39, 40],
    availableSizes: [35, 36, 37, 38],
    color: 'Nude',
    colorHex: '#D4A97A',
    material: 'Cuero nappa',
    sole: 'Suela sintética de alta resistencia',
    insole: 'Plantilla de cuero con acolchado en puntera',
    lastType: 'Horma puntera almendra',
    stock: 7,
    image: I_PUMP_W,
    images: [I_PUMP_W, I_FLAT_W],
    description: 'Stiletto de cuero nappa en nude. Tacón de 8 cm estilizado y estable. El zapato de vestir femenino por excelencia. Forro interior de cuero suave.',
    sku: 'KB-VES-008-NUD',
    isNew: false,
    isFeatured: true,
    isOffer: true,
  },
  {
    id: 9,
    name: 'Zapato Casual Cuero Blanco',
    brand: 'KABUTT',
    category: 'zapatilla',
    gender: 'unisex',
    price: 159.90,
    oldPrice: 199.90,
    discount: 20,
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44],
    availableSizes: [36, 37, 38, 39, 40, 41, 42, 43],
    color: 'Blanco',
    colorHex: '#F5F5F5',
    material: 'Cuero liso premium',
    sole: 'Suela de goma flex',
    insole: 'Plantilla anatómica con soporte de arco',
    lastType: 'Horma redondeada',
    stock: 22,
    image: I_CASUAL_W,
    images: [I_CASUAL_W, I_CASUAL_B],
    description: 'Zapato casual de cuero liso en blanco. Diseño minimalista y versátil. Combina con cualquier outfit casual o smart casual. Muy cómodo para el uso diario.',
    sku: 'KB-ZAP-009-BLA',
    isNew: false,
    isFeatured: true,
    isOffer: true,
  },
  {
    id: 10,
    name: 'Oxford Caoba Artesanal',
    brand: 'KABUTT',
    category: 'vestir',
    gender: 'hombre',
    price: 269.90,
    oldPrice: 329.90,
    discount: 18,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    availableSizes: [40, 41, 42, 43],
    color: 'Caoba',
    colorHex: '#6B2D0F',
    material: 'Cuero genuino polido',
    sole: 'Suela de cuero natural',
    insole: 'Plantilla de cuero acolchada',
    lastType: 'Horma clásica oxford',
    stock: 6,
    image: I_DERBY_BRN2,
    images: [I_DERBY_BRN2, I_DERBY_BRN],
    description: 'Oxford artesanal de cuero polido en caoba. Costura goodyear welt de alta resistencia. Acabados a mano. El zapato que dura generaciones con el cuidado adecuado.',
    sku: 'KB-VES-010-CAO',
    isNew: false,
    isFeatured: false,
    isOffer: true,
  },
  {
    id: 11,
    name: 'Flat Cuero Mujer Negro',
    brand: 'KABUTT',
    category: 'vestir',
    gender: 'mujer',
    price: 149.90,
    oldPrice: null,
    discount: 0,
    sizes: [35, 36, 37, 38, 39, 40],
    availableSizes: [35, 36, 37, 38, 39, 40],
    color: 'Negro',
    colorHex: '#1a1a1a',
    material: 'Cuero genuino suave',
    sole: 'Suela de cuero con refuerzo de goma',
    insole: 'Plantilla de cuero natural',
    lastType: 'Horma puntera estrecha',
    stock: 18,
    image: I_FLAT_W,
    images: [I_FLAT_W, I_PUMP_W],
    description: 'Flat de cuero genuino en negro. Diseño clásico, cómodo y versátil. Ideal para uso oficina o casual. El básico infaltable del guardarropa femenino.',
    sku: 'KB-VES-011-NEG',
    isNew: true,
    isFeatured: false,
    isOffer: false,
  },
  {
    id: 12,
    name: 'Chelsea Boot Cuero Mujer',
    brand: 'KABUTT',
    category: 'botin',
    gender: 'mujer',
    price: 259.90,
    oldPrice: 319.90,
    discount: 19,
    sizes: [35, 36, 37, 38, 39, 40],
    availableSizes: [35, 36, 37, 38, 39],
    color: 'Negro',
    colorHex: '#1a1a1a',
    material: 'Cuero vacuno suave',
    sole: 'Suela de goma texturizada',
    insole: 'Plantilla acolchada premium',
    lastType: 'Horma chelsea clásica',
    stock: 13,
    image: I_CHELSEA_H2,
    images: [I_CHELSEA_H2, I_BOTIN_W],
    description: 'Chelsea boot de cuero vacuno para mujer. Tacón bloque de 4 cm. Elásticos laterales de alta resistencia. Estilo urbano-femenino para la mujer contemporánea.',
    sku: 'KB-BOT-012-NEG',
    isNew: false,
    isFeatured: false,
    isOffer: true,
  },
];

// ============================================================
// Categorías con imágenes de cuero / sin logos
// ============================================================
const shoeCategories = [
  {
    id: 'vestir',
    name: 'Zapatos de Vestir',
    image: I_OXFORD_BLK,
    count: 24,
  },
  {
    id: 'mocasin',
    name: 'Mocasines',
    image: I_LOAFER,
    count: 18,
  },
  {
    id: 'botin',
    name: 'Botines',
    image: I_CHELSEA_H,
    count: 16,
  },
  {
    id: 'zapatilla',
    name: 'Zapatillas Cuero',
    image: I_CASUAL_W,
    count: 12,
  },
  {
    id: 'sandalia',
    name: 'Sandalias',
    image: I_SANDAL_W,
    count: 14,
  },
  {
    id: 'outlet',
    name: 'Outlet',
    image: I_DERBY_BRN,
    count: 40,
  },
];
